version: '3.8'

services:
  nats:
    image: nats:latest
    container_name: nats-server
    ports:
      - "4222:4222"  # Client connections
      - "8222:8222"  # Monitoring (optional)

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"  # Default Redis port
    restart: always
